title: "Ritvik Sharma"
author: "Ritvik Sharma"
email: "rsharma3@stanford.edu"
email_show: "rsharma3 [at] stanford [dot] edu"

description: "PhD student at Stanford University. Research in sparse tensor algebra, compilers, and quantum computing."

# URL config (important for SEO/sitemap/canonical links)
url: "https://ritvik1sharma.github.io"   # no trailing slash
baseurl: ""                              # empty for user site (USERNAME.github.io)

# Social links (used by minima + jekyll-seo-tag)
github_username: ritvik1sharma
google_scholar: "Ritvik Sharma"
linkedin_username: ritvik-sharma-863090144

# Default social preview image (used by seo-tag)
image: /assets/ritviksharma.jpg

show_excerpts: false

# Theme & date format
theme: minima
minima:
  date_format: "%b %-d, %Y"

# Plugins (GitHub Pages supports these)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Nice-to-haves
timezone: "America/Los_Angeles"
markdown: kramdown

# Optional: if you create a custom CSS file (uncomment below)
# custom_css: /assets/custom.css
